version: "3.10"
services:
  web:
    build: .
    command: python main.py
    ports:
      - "80:80"
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
